---
title: "Full Model"
author: "Julia Lawson, UCSB"
date: "2023-09-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(knitr)
library(stargazer)
library(reshape2)
```

# I. Load Parameters

```{r}

x_a = 30
k_a = 100
r_a = 0.8

x_b = 60
k_b = 100
r_b = 0.9

# Movement Parameters
M_ab = 0.2 # Adult movement A -> B 
M_ba = 0.1 # Adult movement B -> A
M_aa = 1 - M_ab
M_bb = 1 - M_ba
D_ab = 0.2 # Larval dispersal A -> B
D_ba = 0.3 # Larval dispersal B -> A
D_aa = 1 - D_ab
D_bb = 1 - D_ba

# Survival Parameters
mu_a = 0.9
mu_b = 0.8
sigma_a = 0.9
sigma_b = 1

timesteps = 100

# Economic Parameters
p_a = 40
c_a = 20
p_b = 30
c_b = 10

# discount factor
delta = 0.95

# Adaptive parameters
size_x_a = 12 #size of the state grid A
size_x_b = 10 #size of B

T = 20 #time horizon for backward induction
small = 0.1

x_a_grid = seq(small,k_a,length.out=size_x_a)
x_b_grid = seq(small,k_b,length.out=size_x_b)

```


```{r}

# Calculate marginal profit
b_a = p_a - c_a
b_b = p_b - c_b

# Functions

## 0. Escapement Function
e_a = function(x_a, h_a) {
  return(x_a - h_a)
}

e_b = function(x_b, h_b) {
  return(x_b - h_b)
}

## 0. Adaptive Escapement Functions

f_a = function(e_a)
{
  grow_a = r_a*e_a*(1-e_a/k_a)
  return(grow_a)
}

f_b = function(e_b)
{
  grow_b = r_b*e_b*(1-e_b/k_b)
  return(grow_b)
}

next_x_a = function(e_a,e_b)
{
  x_a_next = mu_a*M_aa*e_a + mu_b*M_ba*e_b + sigma_a*(D_aa*f_a(e_a) + D_ba*f_b(e_b))
  return(x_a_next)
}

next_x_b = function(e_a,e_b)
{
  x_b_next = mu_b*M_bb*e_b + mu_a*M_ab*e_a + sigma_b*(D_bb*f_b(e_b) + D_ab*f_a(e_a))
  return(x_b_next)
}

pi_a = function(x_a,e_a)
{
  profit_a = b_a*(x_a-e_a)
  return(profit_a)
}

payoff = function(e_a,x_a,x_b,V)
{
  x_a_next = next_x_a(e_a=e_a,e_b=x_b) #e_b=x_b because B is a reserve
  x_b_next = next_x_b(e_a=e_a,e_b=x_b) #e_b=x_b because B is a reserve
  V_next =  bilinear(x_a_grid, x_b_grid, V, x_a_next, x_b_next)
  negout = -(pi_a(x_a=x_a,e_a=e_a) + delta*V_next$z) 
  return(negout)
}

## I. Larval Growth

# Patch-specific population growth Patch A
growth_a = function(e_a, k.=k_a, r.=r_a){
  y_a = r.*e_a*(1-e_a/k.)
  return(y_a)
}
# Patch-specific population growth Patch B
growth_b = function(e_b, k.=k_b, r.=r_b){
  y_b = r.*e_b*(1-e_b/k.)
  return(y_b)
}

#III. Larval contribution at t+1 including survival

new_a_larval = function(y_b = y_b, y_a = y_a, sigma_b.=sigma_b,D_bb. = D_bb, D_ab. = D_ab){
  a_1_larval =  (sigma_a*(y_a*D_aa + y_b*D_ba))
  return(a_1_larval)
}

new_b_larval = function(y_a = y_a, y_b = y_b, sigma_a.=sigma_a, D_aa. = D_aa, D_ba. = D_ba){
  b_1_larval =  (sigma_b*(y_b*D_bb + y_a*D_ab))
  return(b_1_larval)
}

### IV. Adult contribution at t+1 including survival

new_adult_a = function(e_b = e_b, e_a = e_a, mu_a.=mu_a, mu_b.=mu_b, M_bb. = M_bb, M_ab. = M_ab){
  a_1_adult = (mu_a*(e_a*M_aa) + mu_b*(e_b*M_ba))
  return(a_1_adult)
}

new_adult_b = function(e_a = e_a, e_b = e_b, mu_a.=mu_a, mu_b.=mu_b, M_aa. = M_aa, M_ba. = M_ba){
  b_1_adult = (mu_b*(e_b*M_bb) + mu_a*(e_a*M_ab))
  return(b_1_adult)
}

```

## III. Model


```{r}

# Initialize data frames for storing results
results_so <- tibble(
  timestep = integer(), x_a = numeric(), x_b = numeric(), h_a = numeric(), h_b = numeric(), e_star_a = numeric(), e_star_b = numeric()
)

results_non <- tibble(
  timestep = integer(), x_a = numeric(), x_b = numeric(), h_a = numeric(), h_b = numeric(), e_hat_a = numeric(), e_hat_b = numeric()
)

results_adaptive <- tibble(
  timestep = integer(), x_a = numeric(), x_b = numeric(), h_a = numeric(), h_b = numeric(), e_new_a = numeric(), e_new_b = numeric()
)

for(t in 1:timesteps) {

  # SOLE OWNER ESCAPEMENT
  
  # Calculate phi_a and phi_b for e_star
  phi_a <- (b_a/delta - b_a*mu_a*M_aa - b_b*mu_a*M_ab) / 
                   (b_a*sigma_a*D_aa + b_b*sigma_b*D_ab)
  phi_b <- (b_b/delta - b_b*mu_b*M_bb - b_a*mu_b*M_ba) / 
                   (b_b*sigma_b*D_bb + b_a*sigma_a*D_ba)
  
  # Calculate e_star_a and e_star_b
  e_star_a <- (k_a * (r_a - phi_a)) / (2 * r_a)
  e_star_b <- (k_b * (r_b - phi_b)) / (2 * r_b)
  
  # Calculate harvest based on e_star
  h_a = x_a - e_star_a
  h_b = x_b - e_star_b
  
  # Escapement
  e_a_t = x_a - h_a
  e_b_t = x_b - h_b
  
  # Larval production
  y_a_t = growth_a(e_a_t)
  y_b_t = growth_b(e_b_t)
  
  # Larval contribution t+1
  a_t1_larval = new_a_larval(y_a = y_a_t, y_b = y_b_t)
  b_t1_larval = new_b_larval(y_b = y_b_t, y_a = y_a_t)
  
  # Adult contribution t+1
  a_t1_adult = new_adult_a(e_a = e_a_t, e_b = e_b_t)
  b_t1_adult = new_adult_b(e_a = e_a_t, e_b = e_b_t)
  
  # Update stocks in each patch
  x_a_new = a_t1_larval + a_t1_adult
  x_b_new = b_t1_larval + b_t1_adult
  
  # Save results including e_star_a and e_star_b
  results_so <- results_so %>%
    add_row(
      timestep = t,
      x_a = x_a_new,
      x_b = x_b_new,
      h_a = h_a,
      h_b = h_b,
      e_star_a = e_star_a,
      e_star_b = e_star_b)
    
  # Update the stock for next iteration
  x_a <- x_a_new
  x_b <- x_b_new
  
  # NON-COOPERATIVE ESCAPEMENT
  
  # Calculate phi_hat_a and phi_hat_b for e_hat
  phi_hat_a <- (1/delta - mu_a*M_aa) / (sigma_a*D_aa)
  phi_hat_b <- (1/delta - mu_b*M_bb) / (sigma_b*D_bb)
  
  # Calculate e_hat_a and e_hat_b
  e_hat_a <- (k_a * (r_a - phi_hat_a)) / (2 * r_a)
  e_hat_b <- (k_b * (r_b - phi_hat_b)) / (2 * r_b)
  
  # Calculate harvest based on e_hat
  h_a = x_a - e_hat_a
  h_b = x_b - e_hat_b
  
  # Escapement
  e_a_t = x_a - h_a
  e_b_t = x_b - h_b
  
  # Larval production
  y_a_t = growth_a(e_a_t, k_a, r_a)
  y_b_t = growth_b(e_b_t, k_b, r_b)
  
  # Larval contribution t+1
  a_t1_larval = new_a_larval(y_b = y_b_t, y_a = y_a_t)
  b_t1_larval = new_b_larval(y_a = y_a_t, y_b = y_b_t)
  
  # Adult contribution t+1
  a_t1_adult = new_adult_a(e_b = e_b_t, e_a = e_a_t)
  b_t1_adult = new_adult_b(e_a = e_a_t, e_b = e_b_t)
  
  # Update stocks in each patch
  x_a_new = a_t1_larval + a_t1_adult
  x_b_new = b_t1_larval + b_t1_adult
  
  # Save results including e_hat_a and e_hat_b
  results_non <- results_non %>%
    add_row(
      timestep = t,
      x_a = x_a_new,
      x_b = x_b_new,
      h_a = h_a,
      h_b = h_b,
      e_hat_a = e_hat_a,
      e_hat_b = e_hat_b)
    
  # Update the stock
  x_a <- x_a_new
  x_b <- x_b_new
  
  # ADAPTIVE ESCAPEMENT (MPA ESCAPEMENT)
  
  df_all_adaptive = data.frame()
  V_next_adaptive = matrix(0, size_x_a, size_x_b)
  V_adaptive = matrix(0, size_x_a, size_x_b)

  for(time in T:1) {
    for(i in 1:size_x_a) {
      x_a = x_a_grid[i]
      for(j in 1:size_x_b) {
        x_b = x_b_grid[j]
        guess = x_a/2
        low = 0
        high = x_a
        Thing = optim(par = guess, fn = payoff, lower = low, upper = high, x_a = x_a, x_b = x_b, V = V_adaptive, method = 'L-BFGS-B')
        e_a_star = Thing$par
        V_star = -Thing$value
        V_next_adaptive[i, j] = V_star
        df_now = data.frame(time = time, x_a = x_a, x_b = x_b, e_a_star = e_a_star, V_star = V_star)
        df_all_adaptive = bind_rows(df_all_adaptive, df_now)
      }
    }
    V_adaptive = V_next_adaptive
  }
  
  df_inf_adaptive = df_all_adaptive %>% filter(time==1) # optimal decisions and values
  
  # Save results including e_a_star
  results_adaptive <- df_inf_adaptive

}
  
  # New dataframe for NPV values
npv_data <- tibble()

# Calculate NPV for sole owner and non-cooperative escapement using the results_so and results_non dataframes
npv_so <- results_so %>%
  mutate(
    npv_a = sum(b_a * (x_a - e_star_a) * delta^(timestep-1)),
    npv_b = sum(b_b * (x_b - e_star_b) * delta^(timestep-1))
  ) %>%
  mutate(joint_payoff = npv_a + npv_b, scenario = "sole owner") %>% 
  select(e_star_a, e_star_b, npv_a, npv_b,joint_payoff,scenario) %>% 
  rename(e_a = e_star_a, e_b = e_star_b) %>% 
  distinct()

npv_non <- results_non %>%
  mutate(
    npv_a = sum(b_a * (x_a - e_hat_a) * delta^(timestep-1)),
    npv_b = sum(b_b * (x_b - e_hat_b) * delta^(timestep-1))
  ) %>%
  mutate(joint_payoff = npv_a + npv_b, scenario = "non-coop") %>% 
  select(e_hat_a, e_hat_b, npv_a, npv_b,joint_payoff,scenario) %>% 
  rename(e_a = e_hat_a, e_b = e_hat_b) %>% 
  distinct()

#npv_adapt <- results_adaptive %>%
#  filter(x_a = )

# Append NPV results to the npv_data dataframe
npv_data <- bind_rows(npv_so, npv_non)

# Print the resulting dataframe
print(npv_data)


results_adaptive <- df_all_adaptive

```