---
title: "Full Model 2"
author: "Julia Lawson, UCSB"
date: "2023-09-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(knitr)
library(stargazer)
library(reshape2)
library(cowplot)
library(akima)
```

# I. Load Parameters

```{r}

x_a = 60
k_a = 100
r_a = 0.6

x_b = 60
k_b = 100
r_b = 0.6

# Movement Parameters
M_ab = 0.1 # Adult movement A -> B 
M_ba = 0.9 # Adult movement B -> A
M_aa = 1 - M_ab
M_bb = 1 - M_ba
D_ab = 0.1 # Larval dispersal A -> B
D_ba = 0.9 # Larval dispersal B -> A
D_aa = 1 - D_ab
D_bb = 1 - D_ba

# Survival Parameters
mu_a = 1
mu_b = 1
sigma_a = 1
sigma_b = 1

timesteps = 100

# Economic Parameters
p_a = 30
c_a = 20
p_b = 30
c_b = 20

# discount factor
delta = 0.95

# Adaptive parameters
size_x_a = 20 #size of the state grid A
size_x_b = 20 #size of B

T = 100 #time horizon for backward induction
small = 0.1

x_a_grid = seq(small,k_a,length.out=size_x_a)
x_b_grid = seq(small,k_b,length.out=size_x_b)

```

# II. General Functions

```{r}

# Escapement Function
e_a = function(x_a, h_a) {
  return(x_a - h_a)
}

e_b = function(x_b, h_b) {
  return(x_b - h_b)
}

# Harvest Function
h_a = function(x_a, e_a) {
  return(x_a - e_a)
}

h_b = function(x_b, e_b) {
  return(x_b - e_b)
}


# Growth Function

growth_a = function(e_a)
{
  y_a = r_a*e_a*(1-e_a/k_a)
  return(y_a)
}

growth_b = function(e_b)
{
  y_b = r_b*e_b*(1-e_b/k_b)
  return(y_b)
}

# Stock in Next Time Step

next_x_a = function(e_a,e_b)
{
  x_a_new = mu_a*M_aa*e_a + mu_b*M_ba*e_b + sigma_a*(D_aa*growth_a(e_a) + D_ba*growth_b(e_b))
  return(x_a_new)
}

next_x_b = function(e_a,e_b)
{
  x_b_new = mu_b*M_bb*e_b + mu_a*M_ab*e_a + sigma_b*(D_bb*growth_b(e_b) + D_ab*growth_a(e_a))
  return(x_b_new)
}

# Marginal Profit Function

b_a = function(p_a, c_a) {
  return(p_a - c_a)
}

b_b = function(p_b, c_b) {
  return(p_b - c_b)
}


```

# III. Scenario Functions

```{r}

# Sole Owner Scenario

compute_e_star <- function(x_a, x_b, p_a, c_a, mu_a, M_aa, sigma_a, D_aa, k_a, r_a, p_b, c_b, mu_b, M_ab, M_ba, sigma_b, D_ab, D_ba, delta) {
  
  phi_a <- (b_a(p_a, c_a) / delta - b_a(p_a, c_a) * mu_a * M_aa - b_b(p_b, c_b) * mu_a * M_ab) / 
           (b_a(p_a, c_a) * sigma_a * D_aa + b_b(p_b, c_b) * sigma_b * D_ab)
  
  phi_b <- (b_b(p_b, c_b) / delta - b_b(p_b, c_b) * mu_b * M_bb - b_a(p_a, c_a) * mu_b * M_ba) / 
           (b_b(p_b, c_b) * sigma_b * D_bb + b_a(p_a, c_a) * sigma_a * D_ba)
  
  e_star_a <- min(max((k_a * (r_a - phi_a)) / (2 * r_a), 0), x_a)
  e_star_b <- min(max((k_b * (r_b - phi_b)) / (2 * r_b), 0), x_b)
  
  return(list(e_star_a = e_star_a, e_star_b = e_star_b))
}

# Non-cooperative Scenario

compute_e_hat <- function(x_a, x_b, mu_a, M_aa, sigma_a, D_aa, k_a, r_a, mu_b, M_bb, sigma_b, D_bb, k_b, r_b, delta) {
  
  phi_hat_a <- (1 / delta - mu_a * M_aa) / (sigma_a * D_aa)
  phi_hat_b <- (1 / delta - mu_b * M_bb) / (sigma_b * D_bb)
  
  e_hat_a <- min(max((k_a * (r_a - phi_hat_a)) / (2 * r_a), 0), x_a)
  e_hat_b <- min(max((k_b * (r_b - phi_hat_b)) / (2 * r_b), 0), x_b)
  
  return(list(e_hat_a = e_hat_a, e_hat_b = e_hat_b))
}

# Adaptive Scenario
# Profit function (A only)

pi_a = function(x_a, e_a)
{
  profit_a = b_a(p_a, c_a)*(x_a-e_a)
  return(profit_a)
}

payoff = function(e_a, x_a, x_b, V)
{
  x_a_new = next_x_a(e_a=e_a, e_b=x_b) #e_b=x_b because B is a reserve
  x_b_new = next_x_b(e_a=e_a, e_b=x_b) #e_b=x_b because B is a reserve
  V_next =  bilinear(x_a_grid, x_b_grid, V, x_a_new, x_b_new)
  negout = -(pi_a(x_a=x_a, e_a=e_a) + delta*V_next$z) 
  return(negout)
}




```

#IV. Results for Escapement Values

```{r}

initialize_df <- function() {
  tibble(
    x_a = numeric(),
    x_b = numeric(),
    e_star_a = numeric(),
    e_star_b = numeric(),
    e_hat_a = numeric(),
    e_hat_b = numeric(),
    npv_a_star = numeric(),
    npv_b_star = numeric(),
    npv_a_hat = numeric(),
    npv_b_hat = numeric()
  )
}

results <- initialize_df()

# Grid search over x_a_grid and x_b_grid
for(i in seq_along(x_a_grid)) {
  for(j in seq_along(x_b_grid)) {
    
    # Sole owner escapement calculation
    e_star_values <- compute_e_star(x_a = x_a_grid[i], x_b = x_b_grid[j], p_a, c_a, mu_a, M_aa, sigma_a, D_aa, k_a, r_a, p_b, c_b, mu_b, M_ab, M_ba, sigma_b, D_ab, D_ba, delta)
    
    # Non-cooperative escapement calculation
    e_hat_values <- compute_e_hat(x_a = x_a_grid[i], x_b = x_b_grid[j], mu_a, M_aa, sigma_a, D_aa, k_a, r_a, mu_b, M_bb, sigma_b, D_bb, k_b, r_b, delta)
    
    # Calculate NPVs over 100 years
    npv_a_star_total <- sum(sapply(1:100, function(t) b_a(p_a, c_a) * (x_a_grid[i] - e_star_values$e_star_a) * delta^(t-1)))
    npv_b_star_total <- sum(sapply(1:100, function(t) b_b(p_b, c_b) * (x_b_grid[j] - e_star_values$e_star_b) * delta^(t-1)))
    npv_a_hat_total <- sum(sapply(1:100, function(t) b_a(p_a, c_a) * (x_a_grid[i] - e_hat_values$e_hat_a) * delta^(t-1)))
    npv_b_hat_total <- sum(sapply(1:100, function(t) b_b(p_b, c_b) * (x_b_grid[j] - e_hat_values$e_hat_b) * delta^(t-1)))

    # Add the results to the dataframe
    results <- results %>%
      add_row(
        x_a = x_a_grid[i],
        x_b = x_b_grid[j],
        e_star_a = e_star_values$e_star_a,
        e_star_b = e_star_values$e_star_b,
        e_hat_a = e_hat_values$e_hat_a,
        e_hat_b = e_hat_values$e_hat_b,
        npv_a_star = npv_a_star_total,
        npv_b_star = npv_b_star_total,
        npv_a_hat = npv_a_hat_total,
        npv_b_hat = npv_b_hat_total
      )
    
  }
}

# ADAPTIVE ESCAPEMENT
df_all = data.frame()
V_next = matrix(0, size_x_a, size_x_b)
V = matrix(0, size_x_a, size_x_b)

for(t in T:1) {
  for(i in 1:size_x_a) {
    x_a = x_a_grid[i]
    for(j in 1:size_x_b) {
      x_b = x_b_grid[j]
      guess = x_a/2
      low = 0 #lower bound on escapement in A
      high = x_a #upper bound on escapement in A
      Thing = optim(par=guess, fn=payoff, lower=low, upper=high, x_a=x_a, x_b=x_b, V=V, method='L-BFGS-B')
      e_a_star = Thing$par
      V_star = -Thing$value
      V_next[i,j] = V_star
      df_now = data.frame(time=t, x_a=x_a, x_b=x_b, e_a_star=e_a_star, V_star=V_star)
      df_all = rbind(df_all, df_now)
    }
  }
  V = V_next
}

df_inf = df_all %>% filter(time==1) %>% select(-time)

# Merging e_a_star values from df_inf into results based on x_a and x_b
results <- left_join(results, df_inf) %>% 
  select(x_a, x_b, e_star_a, e_star_b, e_hat_a, e_hat_b, e_a_star, npv_a_star, npv_b_star, npv_a_hat, npv_b_hat, V_star) %>% 
  mutate(WTP_A = V_star-npv_a_hat,
         WTA_B = npv_b_hat)

# Print results
print(results)

```

# V. Calculate Willingness-to-Pay and Willingness-to-Accept

```{r}

# How many scenarios would both accept the agreement (WTP_A-WTA_B is positive)
# Conditional on WTP and WTA being positive values

results_filter = results %>% 
  filter(WTP_A > 0) %>% 
  filter(WTA_B > 0) %>%
  mutate(accept = WTP_A-WTA_B) #%>% 
  #mutate(accept = ifelse(e_a_star == 0, NA, WTP_A-WTA_B)) %>% # Positive values are accepted, restriction added so that if e_a_star is 0, there is no agreement.
  #slice_max(accept) # Filtering for highest acceptance
  #filter(accept >= 1) #%>% 
  #count()

# In what scenarios would an agreement be reached (purple)

results_graph = results_filter %>% mutate(Color = ifelse(accept > 0, "purple", "red")) %>%
  ggplot(aes(x = x_a, y= x_b, color = Color))+
  geom_abline(slope=1, linetype="dashed", color="red") +
  geom_point()+
  scale_color_identity() +
  theme_bw() 
  
results_graph # Agreement acceptance is in purple, red is no agreement.

# Creating heatmap with geom_tile based on 'accept' variable
results_graph2 <- results_filter %>%
  ggplot(aes(x = x_a, y = x_b, fill = accept)) + 
  geom_tile() + 
  scale_fill_gradient2(low = "red", high = "purple", mid = "white", 
                       midpoint = 0, limit = c(min(results_filter$accept, na.rm = TRUE), 
                                               max(results_filter$accept, na.rm = TRUE))) + 
  #ggtitle("Low Adult Movement (20%), Low Larval Dispersal (10%)") +
  theme_minimal() +
  labs(fill = "Net Agreement \nAcceptance ($)") +
  theme_bw() +
  xlim(c(0,100)) +
  ylim(c(0,100))

# Print results
print(results_graph2)

#ggsave(here("visuals","high_mvmt_low_dispersal_20.jpg"))

# Other exploratory plots

a <- ggplot(data=results) +
  geom_line(aes(x=x_a,y=e_a_star,color=factor(x_b)),linewidth=1.3) +
  theme_bw() 
a

b <- ggplot(data=results) +
  geom_line(aes(x=x_b,y=e_a_star,color=factor(x_a)),linewidth=1.3) +
  theme_bw() 
b

pv <- ggplot(data=results) +
  geom_line(aes(x=x_a,y=V_star,color=factor(x_b)),linewidth=1.3) +
  theme_bw() 
pv

```



