---
title: "Parameters"
author: "Julia Lawson, UCSB"
date: "2023-09-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(knitr)
library(stargazer)
library(reshape2)
```

# Single set of parameters

```{r}

x_a = 30
k_a = 100
r_a = 0.8

x_b = 60
k_b = 100
r_b = 0.9

# Movement Parameters
M_ab = 0.2 # Adult movement A -> B 
M_ba = 0.1 # Adult movement B -> A
M_aa = 1 - M_ab
M_bb = 1 - M_ba
D_ab = 0.2 # Larval dispersal A -> B
D_ba = 0.3 # Larval dispersal B -> A
D_aa = 1 - D_ab
D_bb = 1 - D_ba

# Survival Parameters
mu_a = 0.9
mu_b = 0.8
sigma_a = 0.9
sigma_b = 1

timesteps = 100

# Economic Parameters
p_a = 40
c_a = 20
p_b = 30
c_b = 10

# discount factor
delta = 0.95

params = c('x_a','k_a','r_a','x_b','k_b','r_b','M_ab','M_ba','M_aa','M_bb','D_ab','D_ba','D_aa','D_bb','mu_a','mu_b','sigma_a','sigma_b','timesteps','p_a','c_a','p_b','c_b','delta')

write.csv(params, here("data","inputs","base_parameters.csv"))

```

### Parameter Sensitivity Analysis

```{r }

# Sensitivity scenario I. Movement

# First, generate the sequences:
M_ab_sens <- seq(0.1, 0.9, by=0.1)
M_ba_sens <- seq(0.1, 0.9, by=0.1)
D_ab_sens <- seq(0.1, 0.9, by=0.1)
D_ba_sens <- seq(0.1, 0.9, by=0.1)

# Initialize the data frame to hold the results:
sensitivity_mvmt <- data.frame()

# Nested for loop to produce combinations:
for (mab in M_ab_sens) {
  for (mba in M_ba_sens) {
    for (dab in D_ab_sens) {
      for (dba in D_ba_sens) {
        sensitivity_mvmt <- rbind(sensitivity_mvmt, c(mab, mba, dab, dba))
      }
    }
  }
}

# Rename columns of the data frame:
colnames(sensitivity_mvmt) <- c('M_ab', 'M_ba', 'D_ab', 'D_ba')

# View the results:
head(sensitivity_mvmt)



```
