---
title: "One Patch Reserve Scenario"
author: "Julia Lawson, UCSB (from Chris Costello)"
date: "2023-09-12"
output: html_document
---

```{r}

rm(list = ls(all = TRUE)) 
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

library(ggplot2)   # Data visualization
library(tidyr)   # Tidy data management
library(dplyr)
library(cowplot)
library(akima)

```

# I. Parameters

```{r}

#This solves patch A's optimal dynamic problem when patch B is a permanent reserve

size_x_a = 12 #size of the state grid A
size_x_b = 10 #size of B

T=20 #time horizon for backward induction
small = 0.1

#adult survival
mu_a = 0.9
mu_b = 0.8

#adult movement
M_ab = 0.05 # Adult movement A -> B 
M_aa = 1-M_ab
M_ba = 0.3 # Adult movement B -> A
M_bb = 1-M_ba

#larval survival
sigma_a = 0.8
sigma_b = 0.85

#larval movement
D_ab = 0.3 # Larval dispersal A -> B
D_aa = 1-D_ab
D_ba = 0.8 # Larval dispersal B -> A
D_bb = 1-D_ba

#larval production
r_a = 0.8
k_a = 100
r_b = 0.8
k_b = 100

#prices
b_a = 1
delta = 0.95

x_a_grid = seq(small,k_a,length.out=size_x_a)
x_b_grid = seq(small,k_b,length.out=size_x_b)

```

# II. Functions

```{r}

f_a = function(e_a)
{
  grow_a = r_a*e_a*(1-e_a/k_a)
  return(grow_a)
}

f_b = function(e_b)
{
  grow_b = r_b*e_b*(1-e_b/k_b)
  return(grow_b)
}

next_x_a = function(e_a,e_b)
{
  x_a_next = mu_a*M_aa*e_a + mu_b*M_ba*e_b + sigma_a*(D_aa*f_a(e_a) + D_ba*f_b(e_b))
  return(x_a_next)
}

next_x_b = function(e_a,e_b)
{
  x_b_next = mu_b*M_bb*e_b + mu_a*M_ab*e_a + sigma_b*(D_bb*f_b(e_b) + D_ab*f_a(e_a))
  return(x_b_next)
}

pi_a = function(x_a,e_a)
{
  profit_a = b_a*(x_a-e_a)
  return(profit_a)
}

#xA,xB,eA are scalars.  V is a matrix corresponding to the values in x_a and x_b
payoff = function(e_a,x_a,x_b,V)
{
  x_a_next = next_x_a(e_a=e_a,e_b=x_b) #e_b=x_b because B is a reserve
  x_b_next = next_x_b(e_a=e_a,e_b=x_b) #e_b=x_b because B is a reserve
  V_next =  bilinear(x_a_grid, x_b_grid, V, x_a_next, x_b_next)
  negout = -(pi_a(x_a=x_a,e_a=e_a) + delta*V_next$z) 
  return(negout)
}

```

# III. Model

```{r}

df_all = data.frame()
V_next = matrix(0,size_x_a,size_x_b)
V = matrix(0,size_x_a,size_x_b)

#Try payoff function
try = payoff(0,10,5,V)

for(t in T:1)
{
  
  for(i in 1:size_x_a)
  {
    x_a = x_a_grid[i]
    for(j in 1:size_x_b)
    {
      x_b = x_b_grid[j]
      guess = x_a/2
      low = 0 #lower bound on escapement in A
      high = x_a #upper bound on escapement in A
      Thing = optim(par=guess,fn=payoff,lower=low,upper=high,x_a=x_a,x_b=x_b,V=V,method='L-BFGS-B')
      e_a_star = Thing$par
      V_star = -Thing$value
      V_next[i,j] = V_star
      df_now = data.frame(time=t,x_a=x_a,x_b=x_b,e_a_star=e_a_star,V_star=V_star)
      df_all = bind_rows(df_all,df_now)
    }
  }
  V = V_next
}

df_inf = df_all %>% filter(time==1)

```

# IV. Visuals

```{r}

PeAxA = ggplot(data=df_inf) +
  geom_line(aes(x=x_a,y=e_a_star,color=factor(x_b)),linewidth=1.3) +
  xlab("Stock, x_a") +
  ylab("Escapeemnt, e_a") +
  theme_bw() 
PeAxA

PeAxB = ggplot(data=df_inf) +
  geom_line(aes(x=x_b,y=e_a_star,color=factor(x_a)),linewidth=1.3) +
  xlab("Stock, x_b") +
  ylab("Escapeemnt, e_a") +
  theme_bw() 
PeAxB

PV=ggplot(data=df_inf) +
  geom_line(aes(x=x_a,y=V_star,color=factor(x_b)),linewidth=1.3) +
  xlab("Stock, x") +
  ylab("Value Fun, V") +
  theme_bw() 
PV

```